"use client";

import { useState } from "react";

type View = "home" | "tasks" | "courses" | "projects" | "people" | "plan" | "path" | "events" | "links";
const nav: { id: View; label: string }[] = [
  { id: "home", label: "This week" }, { id: "tasks", label: "Tasks" }, { id: "courses", label: "Courses" }, { id: "projects", label: "Projects" }, { id: "people", label: "Faculty" }, { id: "plan", label: "Program plan" }, { id: "path", label: "Career path" }, { id: "events", label: "Events" }, { id: "links", label: "Links" },
];
const tasks = [
  ["SEP 10 · 3 PM", "SER 334 · Module 3 exercise", "Confirm the available window and submission format in Canvas."],
  ["SEP 11 · 11:59 PM", "FSE 560 · Module 3 quiz", "Classification week. This dashboard tracks timing only—not course answers."],
  ["SEP 11 · 11:59 PM", "FSE 561 · Lab 1", "Review the assignment requirements and responsible-AI policy before beginning."],
  ["THIS WEEK", "Career strategy appointment", "Bring a current résumé, a public portfolio, and focused questions."],
  ["SEPTEMBER", "Turn a project into a case study", "Frame Smart Industrial Control as a measurable systems story."],
];
const courses = [
  ["FSE 560", "AI Engineering Foundations", "Classification · Module 3", "Mon · 10:30–11:45 · Tempe"],
  ["FSE 561", "AI Ethics & Social Responsibility", "Lab 1 preparation", "Mon · 4:30–5:45 · Hybrid"],
  ["SER 334", "Operating Systems & System Programming", "Module 3 in progress", "Tue / Thu · 1:30–2:45 · Polytechnic"],
];
const faculty = [
  ["Rong Pan", "Professor · Industrial Engineering / Data Science", "Reliability, digital twins, trustworthy AI, and advanced manufacturing.", "A strong fit for making a mixed-reality industrial IoT prototype measurable and research-ready."],
  ["Muslum Ozgur Ozmen", "Assistant Professor · SCAI", "IoT security, industrial control, formal methods, and applied cryptography.", "A strong fit for a safety- and security-aware MQTT control plane."],
  ["Yeonjung Lee", "Assistant Teaching Professor", "Applied AI, ML, NLP, and social-network analysis.", "A helpful connection for sharpening data, methods, and evaluation thinking."],
];

export default function EnglishDashboard() {
  const [view, setView] = useState<View>("home");
  const [done, setDone] = useState<Record<number, boolean>>({});
  const select = (next: View) => { setView(next); window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: "smooth" })); };
  return <main>
    <header className="site-header"><a className="brand" href="#top"><span>ASU</span><strong>Ian · Fall 2026</strong></a><nav aria-label="Primary navigation">{nav.map((item) => <button key={item.id} type="button" className={view === item.id ? "is-active" : ""} onClick={() => select(item.id)}>{item.label}</button>)}<a className="language-toggle" href="/">中文</a></nav></header>
    <div className="page app-shell" id="top">
      {view === "home" && <section className="workspace-panel calendar-panel"><div className="workspace-heading"><div><p className="eyebrow">WEEK AT A GLANCE</p><h2>A calm view of what matters now.</h2></div><p>An operating dashboard for coursework, projects, faculty outreach, and the next career move.</p></div><div className="week-calendar" aria-label="Weekly calendar"><article className="calendar-day"><header><span>WED</span><strong>10</strong></header><div><div className="calendar-item deadline"><strong>SER 334 exercise</strong><span>3:00 PM deadline</span></div></div></article><article className="calendar-day"><header><span>THU</span><strong>11</strong></header><div><div className="calendar-item deadline"><strong>FSE 560 quiz</strong><span>11:59 PM</span></div><div className="calendar-item deadline"><strong>FSE 561 lab</strong><span>11:59 PM</span></div></div></article><article className="calendar-day"><header><span>SAT</span><strong>13</strong></header><div><div className="calendar-item class"><strong>FSE 560 modeling</strong><span>Assignment checkpoint</span></div></div></article><article className="calendar-day is-today"><header><span>SUN</span><strong>14</strong><small>FOCUS</small></header><div><div className="calendar-item deadline"><strong>SER 334 programming</strong><span>Module CP3</span></div></div></article><article className="calendar-day"><header><span>MON</span><strong>15</strong></header><div><div className="calendar-item optional"><strong>Portfolio case study</strong><span>System narrative draft</span></div></div></article></div></section>}
      {view === "tasks" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">OPERATING BOARD</p><h2>Tasks, organized by momentum.</h2></div><p>{Object.values(done).filter(Boolean).length}/{tasks.length} complete. Each item is intentionally specific enough to act on.</p></div><div className="task-group-grid"><article className="task-group"><h3>Priority queue</h3>{tasks.map(([date, title, detail], index) => <article className={"compact-task " + (done[index] ? "is-done" : "")} key={title}><label><input type="checkbox" checked={Boolean(done[index])} onChange={() => setDone((current) => ({ ...current, [index]: !current[index] }))} /><span className="fake-check">✓</span><span><small>{date}</small><strong>{title}</strong></span></label><details><summary>Context</summary><p>{detail}</p></details></article>)}</article><article className="task-group"><h3>How it works</h3><p>This is not a generic task list. It separates hard deadlines, career work, project proof, and faculty outreach so the next choice is visible.</p><div className="next-step"><small>DESIGN PRINCIPLE</small><strong>Reduce cognitive load without hiding useful context.</strong></div></article></div></section>}
      {view === "courses" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">COURSE CONTROL</p><h2>Academic status without the noise.</h2></div><p>The dashboard tracks deadlines and logistics. Course work itself remains the student’s own work.</p></div><div className="course-grid">{courses.map(([code, title, status, schedule], index) => <article className="course-card compact-course" key={code}><div className="course-top"><span>0{index + 1}</span><strong>{status}</strong></div><p className="course-code">{code}</p><h3>{title}</h3><p className="schedule">{schedule}</p><div className="course-week"><small>THIS WEEK</small><strong>Review the individual Canvas item before starting.</strong></div></article>)}</div></section>}
      {view === "projects" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">PARALLEL WORKSTREAMS</p><h2>Build evidence, not just features.</h2></div><p>Each workstream has one visible next move—enough structure to make steady progress.</p></div><div className="workstream-grid"><article className="workstream-card"><div className="workstream-top"><span>PORTFOLIO</span><strong>In progress</strong></div><h3>Smart Industrial Control</h3><p>A mixed-reality and IoT system connecting Quest 3, Unity, MQTT, and ESP32 sensors.</p><div className="next-step"><small>NEXT</small><strong>Draw the system architecture and define one measurable demo outcome.</strong></div></article><article className="workstream-card"><div className="workstream-top"><span>CAREER</span><strong>In progress</strong></div><h3>Role-ready portfolio</h3><p>Translate systems integration, automation, and applied AI experience into clear case studies.</p><div className="next-step"><small>NEXT</small><strong>Prepare one public project story for a recruiter or hiring manager.</strong></div></article><article className="workstream-card"><div className="workstream-top"><span>RESEARCH</span><strong>Explore</strong></div><h3>Reliable industrial AI</h3><p>Use real-time sensor data, digital twins, and human-centered decision support as a research direction.</p><div className="next-step"><small>NEXT</small><strong>Ask a faculty member which small, measurable question is most useful first.</strong></div></article></div></section>}
      {view === "people" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">RESEARCH FIT</p><h2>People to start a conversation with.</h2></div><p>Each card connects a faculty member’s work to a concrete, respectful outreach question.</p></div><div className="mentor-grid">{faculty.map(([name, role, focus, fit]) => <article className="mentor-card" key={name}><p className="mini-label">{role}</p><h3>{name}</h3><div className="focus-list"><span>{focus}</span></div><div className="conversation-starter"><small>WHY THIS FIT</small><strong>{fit}</strong></div><details className="mentor-outreach"><summary>Conversation starter</summary><p>Could I ask which first research question would make this direction small enough to prototype and evaluate well?</p></details></article>)}</div></section>}
      {view === "plan" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">FALL 2026 → SUMMER 2028</p><h2>A two-year program plan.</h2></div><p>A working academic map, meant to be checked with an advisor before formal program decisions.</p></div><div className="program-summary"><div><small>EXPECTED COMPLETION</small><strong>Summer 2028</strong></div><div><small>PROGRAM ROUTE</small><strong>Non-thesis · SER 517</strong></div><div><small>CREDIT TARGET</small><strong>30 credits</strong></div></div><div className="program-timeline"><article className="program-phase current"><div className="phase-head"><div><p className="mini-label">CURRENT</p><h3>Fall 2026</h3><p>Build the foundation</p></div><strong>Core courses + systems practice</strong></div><div className="phase-grid"><section><small>COURSEWORK</small><p>Establish AI engineering foundations, responsible AI framing, and operating-systems fluency.</p></section><section><small>PROJECT</small><p>Make Smart Industrial Control measurable as a portfolio and research artifact.</p></section><section><small>CAREER</small><p>Shape a focused résumé, public portfolio, and internship story.</p></section></div></article><article className="program-phase plan"><div className="phase-head"><div><p className="mini-label">NEXT</p><h3>2027–2028</h3><p>Deepen and demonstrate</p></div><strong>Electives, applied work, and capstone</strong></div><div className="phase-grid"><section><small>COURSEWORK</small><p>Confirm approved concentration and elective choices with the advisor.</p></section><section><small>PROJECT</small><p>Turn the strongest technical direction into a scoped engineering capstone.</p></section><section><small>CAREER</small><p>Apply a growing body of evidence to systems, software, and applied-AI roles.</p></section></div></article></div></section>}
      {view === "path" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">CAREER PATH</p><h2>Build options through evidence.</h2></div><p>This view is a planning tool—not legal or immigration advice.</p></div><div className="planning-grid"><article><b>01</b><h3>Make work visible</h3><p>Use case studies to show the problem, architecture, decisions, and measurable result.</p></article><article><b>02</b><h3>Find the right environment</h3><p>Prioritize software, systems integration, automation, applied AI, and research-adjacent roles.</p></article><article><b>03</b><h3>Keep more than one path open</h3><p>Faculty connections, research roles, and industry roles can reinforce one another.</p></article></div></section>}
      {view === "events" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">SHOW UP</p><h2>Moments worth attending.</h2></div><p>Events are captured as decisions, not clutter.</p></div><div className="event-list"><article className="event-row"><strong>SEP 16</strong><div><h4>Career preparation workshop</h4><span>Bring one question about translating technical experience into a clear story.</span></div></article><article className="event-row"><strong>SEP 18</strong><div><h4>Faculty office hours</h4><span>Ask for feedback on a small, measurable research direction.</span></div></article></div></section>}
      {view === "links" && <section className="workspace-panel"><div className="workspace-heading"><div><p className="eyebrow">OFFICIAL LINKS</p><h2>Useful academic entry points.</h2></div><p>A compact directory for the tools that support day-to-day student work.</p></div><div className="quick-grid"><a href="https://my.asu.edu/" target="_blank" rel="noreferrer"><span>My ASU</span><strong>↗</strong></a><a href="https://canvas.asu.edu/" target="_blank" rel="noreferrer"><span>Canvas</span><strong>↗</strong></a><a href="https://career.asu.edu/careerlink" target="_blank" rel="noreferrer"><span>CareerLink</span><strong>↗</strong></a><a href="https://ai-ms.engineering.asu.edu/resources/" target="_blank" rel="noreferrer"><span>AI MS resources</span><strong>↗</strong></a></div></section>}
      <footer><p>Ian · ASU Fall 2026 Dashboard</p><p>English portfolio view. Personal financial information is intentionally excluded.</p></footer>
    </div>
  </main>;
}
